"""Smart tags — a tag whose article_tag_link rows are generated by a
rule set instead of assigned by hand. See migration 084 for the schema
rationale and smart_rules.py for the shared rule engine (also used by
smart collections).

Smart tags only use ARTICLE_LEVEL_KEYS (title/authors/journal/year/
has_pdf/has_doi/has_pmid/source/has_summary/extraction_status) — no
per-viewer marks — because a materialized tag assignment can't depend
on who's looking at it. See the migration's header comment for the
full reasoning, including why matches are written under the tag's own
creator as `added_by`.
"""
from __future__ import annotations

import logging
from typing import Optional

from sqlalchemy import text as sql_text

from ..ingestion.queue import _get_engine
from . import smart_rules

logger = logging.getLogger(__name__)

SMART_TAG_RULE_KEYS = smart_rules.ARTICLE_LEVEL_KEYS


def filter_rules(rules: dict) -> dict:
    return smart_rules.filter_rules(rules, SMART_TAG_RULE_KEYS)


def sync_tag(tag_id: int, creator_id) -> dict:
    """Re-evaluate a smart tag's rules and materialize the matches into
    article_tag_link under `creator_id`, replacing whatever this tag's
    own previous auto-generated links were (manually-added links —
    is_auto=false — are never touched).

    Returns {"matched": n, "added": n, "removed": n}.
    """
    eng = _get_engine()
    with eng.begin() as conn:
        row = conn.execute(sql_text(
            "SELECT kind, rules FROM article_tag WHERE id = :id"
        ), {"id": tag_id}).mappings().first()
        if not row:
            raise LookupError("tag not found")
        if row["kind"] != "smart":
            raise ValueError("not a smart tag")
        rules = filter_rules(dict(row["rules"] or {}))

        matched_ids = smart_rules.matching_article_ids(rules)

        removed = conn.execute(sql_text(
            "DELETE FROM article_tag_link "
            " WHERE tag_id = :tid AND added_by = CAST(:uid AS uuid) AND is_auto = TRUE"
        ), {"tid": tag_id, "uid": str(creator_id)}).rowcount or 0

        added = 0
        if matched_ids:
            res = conn.execute(sql_text(
                """INSERT INTO article_tag_link (article_id, tag_id, added_by, is_auto, added_at)
                   SELECT x.id, :tid, CAST(:uid AS uuid), TRUE, NOW()
                   FROM (SELECT unnest(CAST(:ids AS uuid[])) AS id) x
                   ON CONFLICT DO NOTHING"""
            ), {"tid": tag_id, "uid": str(creator_id), "ids": matched_ids})
            added = res.rowcount or 0

        conn.execute(sql_text(
            "UPDATE article_tag SET last_synced_at = NOW() WHERE id = :id"
        ), {"id": tag_id})

    logger.info("smart tag %s synced: %d matched, %d added, %d removed",
               tag_id, len(matched_ids), added, removed)
    return {"matched": len(matched_ids), "added": added, "removed": removed}


def sync_due(interval_minutes: int = 20) -> dict:
    """Re-sync every smart tag whose last_synced_at is stale (or NULL).
    Called by the background scheduler (see app.py) and after manual
    edits that don't already trigger their own immediate sync.
    """
    eng = _get_engine()
    with eng.connect() as conn:
        rows = conn.execute(sql_text(
            """SELECT id, created_by FROM article_tag
                WHERE kind = 'smart'
                  AND created_by IS NOT NULL
                  AND (last_synced_at IS NULL
                       OR last_synced_at < NOW() - (:mins || ' minutes')::interval)"""
        ), {"mins": interval_minutes}).all()

    synced, failed = 0, 0
    for tag_id, creator_id in rows:
        try:
            sync_tag(tag_id, creator_id)
            synced += 1
        except Exception:
            logger.exception("smart tag %s sync failed", tag_id)
            failed += 1
    if synced or failed:
        logger.info("smart tags: sync_due synced=%d failed=%d", synced, failed)
    return {"synced": synced, "failed": failed}
