const PDFDocument = require('pdfkit');

const BRAND = 'PrionRead';
const COLORS = { primary: '#1e40af', gray: '#6b7280', light: '#f3f4f6', black: '#111827' };

// ─── Layout helpers ───────────────────────────────────────────────────────────

function header(doc, title, subtitle) {
  doc
    .rect(0, 0, doc.page.width, 70).fill(COLORS.primary)
    .fillColor('white').fontSize(22).font('Helvetica-Bold')
    .text(BRAND, 50, 18)
    .fontSize(11).font('Helvetica')
    .text(title, 50, 44);

  doc.fillColor(COLORS.black).moveDown(0);
  doc.y = 90;

  if (subtitle) {
    doc.fontSize(10).fillColor(COLORS.gray).text(subtitle, 50, doc.y);
    doc.moveDown(0.5);
  }

  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y)
    .strokeColor(COLORS.light).lineWidth(1).stroke();
  doc.moveDown(0.8);
  doc.fillColor(COLORS.black);
}

function sectionTitle(doc, text) {
  doc.moveDown(0.5)
    .fontSize(13).font('Helvetica-Bold').fillColor(COLORS.primary)
    .text(text, 50);
  doc.moveDown(0.3)
    .moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y)
    .strokeColor(COLORS.primary).lineWidth(0.5).stroke();
  doc.moveDown(0.5).font('Helvetica').fillColor(COLORS.black).fontSize(10);
}

function statBox(doc, x, y, label, value) {
  const w = 115, h = 48;
  doc.rect(x, y, w, h).fill(COLORS.light).stroke(COLORS.light);
  doc.fillColor(COLORS.gray).fontSize(8).font('Helvetica')
    .text(label.toUpperCase(), x + 8, y + 7, { width: w - 16 });
  doc.fillColor(COLORS.primary).fontSize(18).font('Helvetica-Bold')
    .text(String(value), x + 8, y + 20, { width: w - 16 });
  doc.fillColor(COLORS.black).font('Helvetica').fontSize(10);
}

function tableRow(doc, cols, widths, x, y, isHeader = false) {
  const rowH = 18;
  if (isHeader) {
    doc.rect(x, y, widths.reduce((s, w) => s + w, 0), rowH).fill('#e0e7ff');
  }
  doc.fillColor(isHeader ? COLORS.primary : COLORS.black)
    .font(isHeader ? 'Helvetica-Bold' : 'Helvetica')
    .fontSize(isHeader ? 8 : 9);

  let cx = x;
  cols.forEach((text, i) => {
    doc.text(String(text ?? '—'), cx + 3, y + 5, { width: widths[i] - 6, lineBreak: false });
    cx += widths[i];
  });
  return y + rowH;
}

function footer(doc) {
  const y = doc.page.height - 30;
  doc.fontSize(8).fillColor(COLORS.gray)
    .text(
      `Generated by ${BRAND} · ${new Date().toISOString().substring(0, 10)}`,
      50, y,
      { align: 'center', width: doc.page.width - 100 }
    );
}

// ─── Public builders ──────────────────────────────────────────────────────────

/**
 * Generates the global lab summary PDF and pipes it into `res`.
 */
function buildGlobalSummaryPDF(res, { dateRange, globalStats, students, topArticles }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition',
    `attachment; filename="prionread-global-report-${new Date().toISOString().substring(0, 10)}.pdf"`
  );
  doc.pipe(res);

  header(doc, 'Global Lab Report', dateRange || 'All time');

  // ── Stats row ──────────────────────────────────────────────────────────────
  sectionTitle(doc, 'Lab Overview');
  const statsY = doc.y;
  statBox(doc, 50,  statsY, 'Students',          globalStats.total_students);
  statBox(doc, 175, statsY, 'Articles',           globalStats.total_articles);
  statBox(doc, 300, statsY, 'Total Reads',        globalStats.total_reads);
  statBox(doc, 425, statsY, 'Avg Score',          globalStats.avg_evaluation_score ?? '—');
  doc.y = statsY + 60;

  doc.fontSize(10)
    .text(`Avg completion rate: ${Math.round((globalStats.avg_completion_rate || 0) * 100)}%`, 50)
    .text(`Milestones: ${globalStats.total_milestones}`, 50)
    .moveDown(0.5);

  // ── Student performance table ──────────────────────────────────────────────
  sectionTitle(doc, 'Student Performance');
  const cols = ['Name', 'Email', 'Assigned', 'Read', 'Evaluated', 'Avg Score', 'Completion'];
  const widths = [110, 140, 55, 45, 60, 60, 65];
  let y = doc.y;
  y = tableRow(doc, cols, widths, 50, y, true);

  for (const s of students) {
    if (y > doc.page.height - 80) {
      footer(doc);
      doc.addPage();
      y = 50;
      y = tableRow(doc, cols, widths, 50, y, true);
    }
    y = tableRow(doc, [
      s.name, s.email,
      s.stats.total_assigned, s.stats.total_read, s.stats.total_evaluated,
      s.stats.avg_score ?? '—',
      `${Math.round((s.stats.completion_rate || 0) * 100)}%`,
    ], widths, 50, y);
  }
  doc.y = y + 10;

  // ── Top articles ──────────────────────────────────────────────────────────
  sectionTitle(doc, 'Most Read Articles');
  const artCols = ['Title', 'Year', 'Times Read', 'Avg Rating'];
  const artWidths = [260, 50, 80, 80];
  y = doc.y;
  y = tableRow(doc, artCols, artWidths, 50, y, true);
  for (const a of (topArticles || []).slice(0, 10)) {
    if (y > doc.page.height - 80) { footer(doc); doc.addPage(); y = 50; }
    y = tableRow(doc, [a.title, a.year || '—', a.times_read, a.avg_rating ?? '—'], artWidths, 50, y);
  }

  footer(doc);
  doc.end();
}

/**
 * Generates a single-student progress PDF and pipes it into `res`.
 */
function buildStudentProgressPDF(res, { student, stats, readingHistory, labComparison }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition',
    `attachment; filename="prionread-student-${student.name.replace(/\s+/g, '-')}-${new Date().toISOString().substring(0, 10)}.pdf"`
  );
  doc.pipe(res);

  header(doc, `Student Progress Report: ${student.name}`, student.email);

  // ── Student stats boxes ────────────────────────────────────────────────────
  sectionTitle(doc, 'Progress Summary');
  const sy = doc.y;
  statBox(doc, 50,  sy, 'Assigned', stats.total_assigned);
  statBox(doc, 175, sy, 'Read',     stats.total_read);
  statBox(doc, 300, sy, 'Evaluated',stats.total_evaluated);
  statBox(doc, 425, sy, 'Avg Score',stats.avg_score ?? '—');
  doc.y = sy + 60;

  // Lab comparison
  if (labComparison) {
    doc.fontSize(10).fillColor(COLORS.gray)
      .text(`Lab rank: #${labComparison.rank} of ${labComparison.total_students} students · ` +
            `Percentile: ${labComparison.percentile}th · ` +
            `Completion: ${Math.round((stats.completion_rate || 0) * 100)}% ` +
            `(lab avg: ${labComparison.avg_lab_completion_rate}%)`);
    doc.fillColor(COLORS.black).moveDown(0.5);
  }

  // ── Reading history table ─────────────────────────────────────────────────
  sectionTitle(doc, 'Reading History');
  const cols = ['Title', 'Year', 'Read Date', 'Score', 'Summary', 'Days'];
  const widths = [190, 45, 75, 55, 55, 50];
  let y = doc.y;
  y = tableRow(doc, cols, widths, 50, y, true);

  for (const entry of readingHistory) {
    if (y > doc.page.height - 80) { footer(doc); doc.addPage(); y = 50; }
    y = tableRow(doc, [
      entry.article?.title || '—',
      entry.article?.year || '—',
      entry.read_date || '—',
      entry.evaluation_score ?? '—',
      entry.summary_created ? 'Yes' : 'No',
      entry.time_to_complete_days ?? '—',
    ], widths, 50, y);
  }

  footer(doc);
  doc.end();
}

module.exports = { buildGlobalSummaryPDF, buildStudentProgressPDF };
