-- Backfill summaries created before the summary_ai_provider column existed.
-- All legacy summaries in this library were generated by Claude (Anthropic).
UPDATE articles
   SET summary_ai_provider = 'anthropic'
 WHERE summary_ai IS NOT NULL
   AND summary_ai <> ''
   AND (summary_ai_provider IS NULL OR summary_ai_provider = '');
